version: "3.5"
services:
  web:
    build: web
    image: appswithdockerandkubernetes/ch08-web:1.0
    ports:
      - 3000:3000
  db:
    build: database
    image: appswithdockerandkubernetes/ch08-db:1.0
    volumes:
      - pets-data:/var/lib/postgresql/data

volumes:
  pets-data: